// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260716085546_ConvertEnumsToEntities")]
    partial class ConvertEnumsToEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server.Model.AllowanceType", b =>
                {
                    b.Property<Guid>("AllowanceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("AllowanceTypeId");

                    b.ToTable("AllowanceTypes");
                });

            modelBuilder.Entity("server.Model.Attendance", b =>
                {
                    b.Property<Guid>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<Guid>("AttendanceStatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<int>("LateMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("OvertimeHours")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RegularHours")
                        .HasColumnType("numeric");

                    b.Property<TimeOnly?>("TimeIn")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("TimeOut")
                        .HasColumnType("time without time zone");

                    b.Property<int>("UndertimeMinutes")
                        .HasColumnType("integer");

                    b.HasKey("AttendanceId");

                    b.HasIndex("AttendanceStatusId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("server.Model.AttendanceStatus", b =>
                {
                    b.Property<Guid>("AttendanceStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("AttendanceStatusId");

                    b.ToTable("AttendanceStatuses");
                });

            modelBuilder.Entity("server.Model.DeductionType", b =>
                {
                    b.Property<Guid>("DeductionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("DeductionTypeId");

                    b.ToTable("DeductionTypes");
                });

            modelBuilder.Entity("server.Model.Department", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("server.Model.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttendanceStatusId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasicSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("EmploymentStatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmploymentTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("PayFrequencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PayrollStatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SalaryTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("EmployeeId");

                    b.HasIndex("AttendanceStatusId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.HasIndex("EmploymentStatusId");

                    b.HasIndex("EmploymentTypeId");

                    b.HasIndex("PayFrequencyId");

                    b.HasIndex("PayrollStatusId");

                    b.HasIndex("PositionId");

                    b.HasIndex("SalaryTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("server.Model.EmployeeAllowance", b =>
                {
                    b.Property<Guid>("EmployeeAllowanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllowanceTypeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("EmployeeAllowanceId");

                    b.HasIndex("AllowanceTypeId");

                    b.HasIndex("EmployeeId", "AllowanceTypeId")
                        .IsUnique();

                    b.ToTable("EmployeeAllowances");
                });

            modelBuilder.Entity("server.Model.EmployeeDeduction", b =>
                {
                    b.Property<Guid>("EmployeeDeductionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("DeductionTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.HasKey("EmployeeDeductionId");

                    b.HasIndex("DeductionTypeId");

                    b.HasIndex("EmployeeId", "DeductionTypeId")
                        .IsUnique();

                    b.ToTable("EmployeeDeductions");
                });

            modelBuilder.Entity("server.Model.EmploymentStatus", b =>
                {
                    b.Property<Guid>("EmploymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("EmploymentStatusId");

                    b.ToTable("EmploymentStatuses");
                });

            modelBuilder.Entity("server.Model.EmploymentType", b =>
                {
                    b.Property<Guid>("EmploymentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("EmploymentTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EmploymentTypes");
                });

            modelBuilder.Entity("server.Model.PayFrequency", b =>
                {
                    b.Property<Guid>("PayFrequencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PayFrequencyId");

                    b.ToTable("PayFrequencies");
                });

            modelBuilder.Entity("server.Model.Payroll", b =>
                {
                    b.Property<Guid>("PayrollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasicPay")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("GrossPay")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("NetPay")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("PayrollPeriodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PayrollStatusId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAllowances")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalDeductions")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("PayrollId");

                    b.HasIndex("PayrollPeriodId");

                    b.HasIndex("PayrollStatusId");

                    b.HasIndex("EmployeeId", "PayrollPeriodId")
                        .IsUnique();

                    b.ToTable("Payrolls");
                });

            modelBuilder.Entity("server.Model.PayrollAllowance", b =>
                {
                    b.Property<Guid>("PayrollAllowanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllowanceTypeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("PayrollId")
                        .HasColumnType("uuid");

                    b.HasKey("PayrollAllowanceId");

                    b.HasIndex("AllowanceTypeId");

                    b.HasIndex("PayrollId");

                    b.ToTable("PayrollAllowances");
                });

            modelBuilder.Entity("server.Model.PayrollDeduction", b =>
                {
                    b.Property<Guid>("PayrollDeductionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("DeductionTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PayrollId")
                        .HasColumnType("uuid");

                    b.HasKey("PayrollDeductionId");

                    b.HasIndex("DeductionTypeId");

                    b.HasIndex("PayrollId");

                    b.ToTable("PayrollDeductions");
                });

            modelBuilder.Entity("server.Model.PayrollPeriod", b =>
                {
                    b.Property<Guid>("PayrollPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PayDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("PayrollPeriodId");

                    b.ToTable("PayrollPeriods");
                });

            modelBuilder.Entity("server.Model.PayrollStatus", b =>
                {
                    b.Property<Guid>("PayrollStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("PayrollStatusId");

                    b.ToTable("PayrollStatuses");
                });

            modelBuilder.Entity("server.Model.Position", b =>
                {
                    b.Property<Guid>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("PositionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("server.Model.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("server.Model.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("server.Model.SalaryType", b =>
                {
                    b.Property<Guid>("SalaryTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("SalaryTypeId");

                    b.ToTable("SalaryTypes");
                });

            modelBuilder.Entity("server.Model.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("server.Model.Attendance", b =>
                {
                    b.HasOne("server.Model.AttendanceStatus", "AttendanceStatus")
                        .WithMany("Attendances")
                        .HasForeignKey("AttendanceStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Model.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendanceStatus");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("server.Model.Employee", b =>
                {
                    b.HasOne("server.Model.AttendanceStatus", "AttendanceStatus")
                        .WithMany("Employees")
                        .HasForeignKey("AttendanceStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Model.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Model.EmploymentStatus", "EmploymentStatus")
                        .WithMany("Employees")
                        .HasForeignKey("EmploymentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Model.EmploymentType", "EmploymentType")
                        .WithMany("Employees")
                        .HasForeignKey("EmploymentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Model.PayFrequency", "PayFrequency")
                        .WithMany("Employees")
                        .HasForeignKey("PayFrequencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Model.PayrollStatus", "PayrollStatus")
                        .WithMany("Employees")
                        .HasForeignKey("PayrollStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Model.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Model.SalaryType", "SalaryType")
                        .WithMany("Employees")
                        .HasForeignKey("SalaryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("AttendanceStatus");

                    b.Navigation("Department");

                    b.Navigation("EmploymentStatus");

                    b.Navigation("EmploymentType");

                    b.Navigation("PayFrequency");

                    b.Navigation("PayrollStatus");

                    b.Navigation("Position");

                    b.Navigation("SalaryType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.Model.EmployeeAllowance", b =>
                {
                    b.HasOne("server.Model.AllowanceType", "AllowanceType")
                        .WithMany("EmployeeAllowances")
                        .HasForeignKey("AllowanceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Model.Employee", "Employee")
                        .WithMany("EmployeeAllowances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AllowanceType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("server.Model.EmployeeDeduction", b =>
                {
                    b.HasOne("server.Model.DeductionType", "DeductionType")
                        .WithMany("EmployeeDeductions")
                        .HasForeignKey("DeductionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Model.Employee", "Employee")
                        .WithMany("EmployeeDeductions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeductionType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("server.Model.Payroll", b =>
                {
                    b.HasOne("server.Model.Employee", "Employee")
                        .WithMany("Payrolls")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Model.PayrollPeriod", "PayrollPeriod")
                        .WithMany("Payrolls")
                        .HasForeignKey("PayrollPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Model.PayrollStatus", "PayrollStatus")
                        .WithMany("Payrolls")
                        .HasForeignKey("PayrollStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayrollPeriod");

                    b.Navigation("PayrollStatus");
                });

            modelBuilder.Entity("server.Model.PayrollAllowance", b =>
                {
                    b.HasOne("server.Model.AllowanceType", "AllowanceType")
                        .WithMany("PayrollAllowances")
                        .HasForeignKey("AllowanceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Model.Payroll", "Payroll")
                        .WithMany("PayrollAllowances")
                        .HasForeignKey("PayrollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AllowanceType");

                    b.Navigation("Payroll");
                });

            modelBuilder.Entity("server.Model.PayrollDeduction", b =>
                {
                    b.HasOne("server.Model.DeductionType", "DeductionType")
                        .WithMany("PayrollDeductions")
                        .HasForeignKey("DeductionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Model.Payroll", "Payroll")
                        .WithMany("PayrollDeductions")
                        .HasForeignKey("PayrollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeductionType");

                    b.Navigation("Payroll");
                });

            modelBuilder.Entity("server.Model.RefreshToken", b =>
                {
                    b.HasOne("server.Model.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.Model.User", b =>
                {
                    b.HasOne("server.Model.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("server.Model.AllowanceType", b =>
                {
                    b.Navigation("EmployeeAllowances");

                    b.Navigation("PayrollAllowances");
                });

            modelBuilder.Entity("server.Model.AttendanceStatus", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("server.Model.DeductionType", b =>
                {
                    b.Navigation("EmployeeDeductions");

                    b.Navigation("PayrollDeductions");
                });

            modelBuilder.Entity("server.Model.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("server.Model.Employee", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("EmployeeAllowances");

                    b.Navigation("EmployeeDeductions");

                    b.Navigation("Payrolls");
                });

            modelBuilder.Entity("server.Model.EmploymentStatus", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("server.Model.EmploymentType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("server.Model.PayFrequency", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("server.Model.Payroll", b =>
                {
                    b.Navigation("PayrollAllowances");

                    b.Navigation("PayrollDeductions");
                });

            modelBuilder.Entity("server.Model.PayrollPeriod", b =>
                {
                    b.Navigation("Payrolls");
                });

            modelBuilder.Entity("server.Model.PayrollStatus", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Payrolls");
                });

            modelBuilder.Entity("server.Model.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("server.Model.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("server.Model.SalaryType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("server.Model.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
